# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b45fcb1d642423f2dd318ecc1c9aeda83e235cfed3c6103e2d3267dfe737ed35f58ebc0b6fa5ae31e0eb2f5c10706284716db3aeba6b01ba2fba24e2f9b1071

test:
  secret_key_base: 3410af5fd1a27297b5e509c22109bcb4ec5d4af420c762cd2eeffad5ac3c7e4ce965164ebe54dd8c63ea45548a3b5017db5ed5dc034a95dc55333c04fa5620ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
