# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cc510b35090949aca88724dac679ca78635af21515fb389640d2cafdb16c3c39ff1ce9420ac5893b26ed17eaf8a9467c6370ef402d8d0615efec1505e2028d0

test:
  secret_key_base: 9533ddbbc43b66f3257a528f5cfa265fb2234f110efb973fcafb12fb9a5c56399650c0108c8f132c3c8a39a1ebbdf6af6c7e0423ef22ff80e07229a5c6282ef1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
